baseURL = 'https://spc.scetrov.live/'
languageCode = 'en-us'
title = '🍓 Strawberry Pudding Craft'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "en"
Paginate = 10
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  body_classes = "avenir black bg-washed-red"
  author = "Scetrov"
  favicon = "images/favicon.png"
  description = "A vanilla-like Minecraft Server"
  background_color_class = "bg-dark-red"
  recent_posts_number = 3